MOSIP-29247 : PMP UI: All active partners should be displayed in "Partner Name" dropdown for partner policy mapping.
mosip/partner-management-portal pull request #179
Opened 2023-09-11 10:18 UTC by GOKULRAJ136

2023-09-15 07:06 UTC, balaji-alluru approved these changes

2023-11-08 05:41 UTC, aranaravi commented
Code is specific to partner please create component as autocomplete and use it.

2024-02-05 06:51 UTC, aranaravi requested changes

2024-02-05 06:51 UTC, aranaravi commented on pmp-ui/src/assets/entity-spec/policy-mapping.json
Change the input type to autocomplete instead of dropdownpartner

2024-02-05 08:30 UTC, GOKULRAJ136 commented on pmp-ui/src/assets/entity-spec/policy-mapping.json
We are only using dropdownpartner as an input field, so if we provide autocomplete as an input, it won't work.

2024-02-05 10:09 UTC, aranaravi approved these changes

2024-02-05 10:56 UTC, closed without merging