MOSIP-30787
mosip/partner-management-portal pull request #201
Opened 2023-12-19 12:48 UTC by jayesh12234

2023-12-19 12:55 UTC, syedsalman3753 requested changes
Please add Titlte message in the PR 

```
[MOSIP-30787] updated base image in pmptest's Dockerfile
```

2023-12-19 13:13 UTC, syedsalman3753 approved these changes

2024-01-12 09:30 UTC, kamalsinghthoughtworks approved these changes

2024-01-22 11:49 UTC, aranaravi approved these changes

2024-01-22 11:55 UTC, merged