MOSIP-35026: UI Development of Download FTM Chip Certificate.
mosip/partner-management-portal pull request #769
Opened 2024-09-18 06:10 UTC by Anil-kumar-Majji

2024-09-18 06:30 UTC, mayuradesh requested changes
create reusable code and don't copy paste

2024-09-18 15:56 UTC, Anil-kumar-Majji commented
> create reusable code and don't copy paste

Done @mayuradesh

2024-09-19 06:18 UTC, mayuradesh requested changes
pass customStyles as attribute instead of popupStyleSet

2024-09-19 10:17 UTC, mayuradesh approved these changes

2024-09-19 10:29 UTC, mayuradesh approved these changes

2024-09-19 10:31 UTC, merged