MOSIP-35888 PMS UI automation first cut
mosip/partner-management-portal pull request #772
Opened 2024-09-18 12:07 UTC by jayesh12234

**Page Object Model (POM) Setup:**
- Introduced the POM design pattern to manage UI elements and interactions in a modular and reusable manner.
- Each page of the application has its own corresponding page class, encapsulating the elements and functions for that specific page.

**Complete Registration and Login Flow Automation:**
- Automated the entire "Register User" and "Login" flows.
- These flows utilize the newly created page classes to interact with different screens, ensuring robust test execution and improved reusability of the code.

**Common Methods Page Class:**
- Developed a base page class containing common utility methods that are shared across multiple page classes, such as waiting for elements, clicking, sending text, etc.
- This approach reduces code duplication and ensures consistency across test scripts.

**Individual Page Classes:**
- Created dedicated page classes for different screens of the application (e.g., LoginPage, RegistrationPage, HomePage).
- These page classes house the locators and methods for interacting with the elements specific to those screens, adhering to the POM principles.

2024-09-20 12:01 UTC, mohanachandran-s requested changes

2024-09-20 12:01 UTC, mohanachandran-s commented on uitest-pmprevamp/src/main/resources/testngFile/testng.xml
Format the xml file

2024-10-03 07:20 UTC, mohanachandran-s approved these changes

2024-10-03 08:07 UTC, mayuradesh approved these changes

2024-10-03 08:14 UTC, merged