MOSIP-36886, MOSIP-36887: UI Development & integration of Active Associated Policy Groups Error pop-up.
mosip/partner-management-portal pull request #925
Opened 2024-11-13 12:05 UTC by Anil-kumar-Majji

2024-11-14 05:04 UTC, mayuradesh approved these changes

2024-11-14 05:15 UTC, mayuradesh requested changes
1. `LoadingDots `this is not a proper function name. make it a component and not a method.
2. `showErrorPopup `this is not a meaningful state variable name. Change it to `showAlertErrorMessage`.
3. Checking for '`PMS_POL_056`' and getting `countOfAssociatedPolicies `is very specific to Deactivate Policy Group, why is that code added to common component `DeactivatePopup`?

2024-11-14 13:02 UTC, SwethaKrish4 requested changes
1.  remove if(popupData.isDeactivatePolicyGroup) this check, since this is only used for DeactivatePolicyGroup
2. id="active_policies_detected_msg_btn" change this to alert_error_popup_okay_btn
3. remove popupData.isDeactivateDevice, popupData.isDeactivateFtm etc in headerKeyName(keep only headerKeyName)
4. change id="deactivate_cancel_btn" to deactivate_policy_group_cancel_btn
5. change id="deactivate_submit_btn" to deactivate_policy_group_confirm_btn

2024-11-15 05:13 UTC, mayuradesh approved these changes

2024-11-15 05:13 UTC, merged